export const TEST_IDS = {
  auth: {
    loginForm: 'auth-login-form',
    registerForm: 'auth-register-form',
    resetForm: 'auth-reset-form',
    loginEmailInput: 'auth-login-email-input',
    loginPasswordInput: 'auth-login-password-input',
    loginSubmitButton: 'auth-login-submit-button',
    loginGoogleButton: 'auth-login-google-button',
    switchToRegisterButton: 'auth-switch-to-register-button',
    registerFirstNameInput: 'auth-register-first-name-input',
    registerLastNameInput: 'auth-register-last-name-input',
    registerEmailInput: 'auth-register-email-input',
    registerPhoneInput: 'auth-register-phone-input',
    registerPasswordInput: 'auth-register-password-input',
    registerConfirmPasswordInput: 'auth-register-confirm-password-input',
    registerSubmitButton: 'auth-register-submit-button',
    resetEmailInput: 'auth-reset-email-input',
    resetSubmitButton: 'auth-reset-submit-button',
  },
  pinpad: {
    layout: 'pinpad-layout',
    input: 'pinpad-input',
    logoutButton: 'pinpad-logout-button',
    changeOrganizationButton: 'pinpad-change-organization-button',
    key: (key: string) => `pinpad-key-${key.toLowerCase()}`,
    demoHint: (pin: string) => `pinpad-demo-hint-${pin}`,
  },
  demo: {
    organizationSelectButton: (restaurantId: string) => `demo-organization-select-button-${restaurantId}`,
  },
  booking: {
    addButton: 'booking-add-button',
    editButton: (bookingId: string) => `booking-item-edit-button-${bookingId}`,
    cancelButton: (bookingId: string) => `booking-item-cancel-button-${bookingId}`,
  },
  menu: {
    addMenuButton: 'menu-add-menu-button',
    addCategoryMenuItem: 'menu-add-category-menu-item',
    addItemMenuItem: (itemType: string) => `menu-add-item-menu-item-${itemType}`,
    firstCategoryButton: 'menu-first-category-button',
    categoryDialog: 'menu-category-dialog',
    categoryNameInput: 'menu-category-name-input',
    categoryDescriptionInput: 'menu-category-description-input',
    itemDialog: 'menu-item-dialog',
    itemCategoryInput: 'menu-item-category-input',
    itemTypeInput: 'menu-item-type-input',
    itemNameInput: 'menu-item-name-input',
    itemPriceInput: 'menu-item-price-input',
    itemDescriptionInput: 'menu-item-description-input',
    itemIngredientsInput: 'menu-item-ingredients-input',
    dialogSaveButton: 'menu-dialog-save-button',
    dialogCancelButton: 'menu-dialog-cancel-button',
  },
  session: {
    banner: 'session-banner',
    bannerRestaurant: 'session-banner-restaurant',
    bannerTotal: 'session-banner-total',
    drawer: 'session-drawer',
    drawerHeader: 'session-drawer-header',
    tabOrders: 'session-tab-orders',
    tabSplit: 'session-tab-split',
    tabInvite: 'session-tab-invite',
    ordersEmpty: 'session-orders-empty',
    orderItem: (id: string) => `session-order-item-${id}`,
    splitModeFullPay: 'session-split-full-pay',
    splitModeEqual: 'session-split-equal',
    splitModeItemized: 'session-split-itemized',
    splitMyTotal: 'session-split-my-total',
    tipPreset: (pct: number) => `session-tip-preset-${pct}`,
    tipCustomInput: 'session-tip-custom-input',
    tipCustomSubmit: 'session-tip-custom-submit',
    tipCurrent: 'session-tip-current',
    sosButton: 'session-sos-button',
    payButton: 'session-pay-button',
    inviteQr: 'session-invite-qr',
    participantList: 'session-participant-list',
    participant: (uid: string) => `session-participant-${uid}`,
    closeDrawer: 'session-close-drawer',
    claimItem: (id: string) => `session-claim-item-${id}`,
    billTotal: 'session-bill-total',
    billPaid: 'session-bill-paid',
    billRemaining: 'session-bill-remaining',
  },
} as const;

export const byTestId = (testId: string): string => `[data-testid="${testId}"]`;
